### ISSUE TITLE
Bootloader hanging on field application -2560

### ISSUE THREAD

**Issue by andrebstv** [codebendercc/Ariadne-Bootloader#23]
Hi,

I couldn`t help but notice the bootloader is not protected by a WDT. I have a device on the field that from time to time hangs, and as I can see from logs writen on a SD card It does in the bootloader section. (it shows a "reboot" string on the log and then no "Power ON" string which is the very first thing it does on app start).

I`ve changed the bootloader code to include proper wdt protection, but I`m unable to compile it... It may sound like a noob error, but it fails on the memcpy_PF... I`ve seen previous ppl having this error but no solution to it.

I do compile on windows, using the WinAVR toolchain.

Where should I change on the makefile so I can compile it? Tried everywhere and still got this error.

Note that I would gladly post the wdt fix once I`ve tested.

**Comment by LoathingKernel** [comment]
What I think that will fix your issue is downloading the AVR toolchain from here http://www.atmel.com/tools/ATMELAVRTOOLCHAINFORWINDOWS.aspx

**Comment by andrebstv** [comment]
I solved the compiling issue. Apparently you need to compile the target atmega328 to generate some .o files that are used when compiling the atmega2560 target and the debug2560 target.

It`s a bug on the makefile. I won`t try to fix that. I might break something... my makefileism`s skill are not good.

I will do some more testing with the modded bootloader, that includes the wdt, and if successful post the fixes.

**Comment by andrebstv** [comment]
Correction: it's actually a difference on the  pgmspace.h from the winavr toolchain vs the atmel toolchain.
The make file is correct.

**Comment by andrebstv** [comment]
Created the pull request. Still sometimes the signature seems to be corrupted and the bootloader doesn`t start the application.... a fresh upload solves this. Main thing is that the board is no longer hangable.

**Comment by andrebstv** [comment]
The problem was fixed, but now everytime the application resets it hangs on the bootloader. Never allowing the user app to run. I even tried to enforce the eeprom signature write on the user app, to trick the bootloader but no avail.

A fresh upload, that is a firmware "update", fixes the problem...Probably deactivating the eeprom signature check fixes it... but that seems a bit like a cludge.

Help please?

**Comment by LoathingKernel** [comment]
Can you give me more information? Have you tried increasing the WDT timer to give more time for the bootloader to load?

**Comment by LoathingKernel** [comment]
This issue was moved to LoathingKernel/Ariadne-Bootloader#5
