### ISSUE TITLE
Add uploading of the sketch through SD

### ISSUE THREAD

**Issue by LoathingKernel** [codebendercc/Ariadne-Bootloader#3]
Since most ethernet shields have an SD card socket this might would be useful to have. 
I am just leaving it here to see how many people are interested in having this feature integrated to
Ariadne.

It has been done before so, probably, i will be using the existing solution if it fits nicely with the rest of the code.

**Comment by q2dg** [comment]
+1 !!!

**Comment by FloeHerrmann** [comment]
+1

**Comment by Apollon77** [comment]
+1, I currently try https://github.com/FleetProbe/MicroBridge-Arduino-ATMega2560

**Comment by q2dg** [comment]
Another option is https://github.com/zevero/avr_boot

**Comment by LoathingKernel** [comment]
This issue was moved to LoathingKernel/Ariadne-Bootloader#1
