### ISSUE TITLE
Please specify fuses for alternative ICSP programmer.

### ISSUE THREAD

**Issue by puhycz** [codebendercc/Ariadne-Bootloader#36]
Hello,

I try program this Ariadne-Bootloader to Arduino Mega2560 by [ASIX PRESTO](http://www.asix.net/prg_presto.htm) Programmer (I have only this programmer).

When I open hex file, there are some alert about Little or Big Endian:

![image](https://cloud.githubusercontent.com/assets/6555850/20219728/02fc1968-a82b-11e6-8ec9-afe4f9d9eb86.png)

Please help me with settings fuses. Is somewhere specify fuses for ariadne-bootloader?

![mega2560conf](https://cloud.githubusercontent.com/assets/6555850/20219668/c4f31bee-a82a-11e6-86fd-db7b6d2cbb75.png)

I try default fuses with SPI prog. enabled, but it is not function ...

Many thanks,

Jan

**Comment by puhycz** [comment]
I finally solved it with standard avrdude.

Step by step is here (in Czech language):
https://www.puhy.cz/blog/lan-bootloader-pro-arduino-mega-2560-atmel-atmega-2560/

**Comment by loathingKernel** [comment]
This issue was moved to LoathingKernel/Ariadne-Bootloader#20
